name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk --no-install-recommends
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: pip install -U sphinx; pip install sphinx-rtd-theme sphinx-last-updated-by-git
    - name: Build documentation
      run: python ./build.py
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output/html
        force_orphan: true
